databases:
  - name: E-commerce
    databaseName: postgresql
    user: dheeraj

services:
  - type: web
    name: E-commerce
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: E-commerce
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false